"""Phase 1.1: UUID v7 event_id + event_delivery table

Revision ID: (autogenerate)
Revises: (previous head)
Create Date: 2026-03-03

IMPORTANT: 既存の detection_events テーブルのPKを integer → UUID に変更する。
           既存のテストデータは削除される。本番データがある場合は別途マイグレーション戦略が必要。

手順:
  1. alembic revision --autogenerate -m "phase1_1_uuid_event_id"
  2. 生成されたファイルを確認・編集（autogenerate は PK変更を正しく検出しない場合がある）
  3. alembic upgrade head

以下は手動で記述すべきマイグレーション内容:
"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects.postgresql import UUID, JSONB


def upgrade() -> None:
    # ── Step 1: 旧テーブルのデータをバックアップ（テストデータなら不要） ──
    # op.execute("CREATE TABLE detection_events_backup AS SELECT * FROM detection_events")

    # ── Step 2: 旧 detection_events テーブルを削除して再作成 ──
    # autogenerate では PK 型変更 (int→UUID) が検出されないため手動で記述
    op.drop_table("detection_events")

    op.create_table(
        "detection_events",
        sa.Column("event_id", UUID(as_uuid=True), primary_key=True,
                  comment="UUID v7 generated by edge device"),
        sa.Column("device_id", sa.String(30),
                  sa.ForeignKey("devices.device_id"), nullable=False),
        sa.Column("event_type", sa.String(32), nullable=False,
                  server_default="detection",
                  comment="detection / heartbeat / alert"),
        sa.Column("occurred_at", sa.DateTime(timezone=True), nullable=False,
                  server_default=sa.text("CURRENT_TIMESTAMP"),
                  comment="デバイス側の検知時刻"),
        sa.Column("received_at", sa.DateTime(timezone=True), nullable=False,
                  server_default=sa.text("CURRENT_TIMESTAMP"),
                  comment="サーバ受信時刻"),
        sa.Column("detection_type", sa.String(20), nullable=True),
        sa.Column("confidence", sa.Numeric(5, 4), nullable=True),
        sa.Column("image_path", sa.String(500), nullable=True),
        sa.Column("image_url", sa.String(255), nullable=True),
        sa.Column("ip_address", sa.String(45), nullable=True),
        sa.Column("ip_geolocation_region", sa.String(100), nullable=True),
        sa.Column("distance_from_registered_km", sa.Numeric(10, 3), nullable=True),
        sa.Column("location_mismatch", sa.Boolean, nullable=False,
                  server_default=sa.text("false")),
        sa.Column("payload_json", JSONB, nullable=True,
                  comment="生ペイロード保存"),
    )

    # ── Step 3: インデックス作成 ──
    op.create_index(
        "idx_events_device_time",
        "detection_events",
        ["device_id", "occurred_at"],
    )

    # ── Step 4: event_delivery テーブル作成 ──
    op.create_table(
        "event_delivery",
        sa.Column("event_id", UUID(as_uuid=True),
                  sa.ForeignKey("detection_events.event_id"),
                  primary_key=True),
        sa.Column("state", sa.String(16), nullable=False,
                  server_default="received"),
        sa.Column("retry_count", sa.Integer, nullable=False,
                  server_default="0"),
        sa.Column("last_attempt_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("acked_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "state IN ('received', 'processing', 'completed', 'failed')",
            name="event_delivery_state_check",
        ),
    )


def downgrade() -> None:
    op.drop_table("event_delivery")
    op.drop_table("detection_events")

    # 旧テーブルを復元（integer PK版）
    op.create_table(
        "detection_events",
        sa.Column("id", sa.Integer, primary_key=True, autoincrement=True),
        sa.Column("device_id", sa.String(30),
                  sa.ForeignKey("devices.device_id"), nullable=False),
        sa.Column("detected_at", sa.DateTime(timezone=True), nullable=False,
                  server_default=sa.text("CURRENT_TIMESTAMP")),
        sa.Column("detection_type", sa.String(20), nullable=True),
        sa.Column("confidence", sa.Numeric(5, 4), nullable=True),
        sa.Column("image_path", sa.String(500), nullable=True),
        sa.Column("image_url", sa.String(255), nullable=True),
        sa.Column("ip_address", sa.String(45), nullable=True),
        sa.Column("ip_geolocation_region", sa.String(100), nullable=True),
        sa.Column("distance_from_registered_km", sa.Numeric(10, 3), nullable=True),
        sa.Column("location_mismatch", sa.Boolean, nullable=False,
                  server_default=sa.text("false")),
    )
