[Service]
ExecStartPre=-/usr/bin/mmcli -m 0 --location-set-supl-server=supl.google.com:7276
ExecStartPre=-/usr/bin/mmcli -m 0 --location-enable-agps-msb
ExecStartPre=-/usr/bin/mmcli -m 0 --location-enable-gps-nmea
ExecStartPre=-/usr/bin/mmcli -m 0 --location-enable-gps-raw
