"""models.py -- DB models (Phase 1.1 update: UUID v7 event_id + event_delivery)"""
import uuid
from datetime import datetime, timezone
from sqlalchemy import (
    Boolean, CheckConstraint, Column, DateTime,
    ForeignKey, Integer, Numeric, String, UniqueConstraint, text,
)

from sqlalchemy.dialects.postgresql import INET, JSONB, UUID
from sqlalchemy.orm import relationship

from .database import Base


# =============================================================================
# User
# =============================================================================

class User(Base):
    __tablename__ = "users"

    user_id = Column(
        UUID(as_uuid=True), primary_key=True,
        default=uuid.uuid4, server_default=text("gen_random_uuid()"),
    )
    email = Column(String(255), unique=True, nullable=False)
    phone_number = Column(String(20), nullable=True)
    password_hash = Column(String(255), nullable=False)
    created_at = Column(
        DateTime(timezone=True), nullable=False,
        server_default=text("CURRENT_TIMESTAMP"),
    )
    updated_at = Column(
        DateTime(timezone=True), nullable=False,
        server_default=text("CURRENT_TIMESTAMP"),
    )

    devices = relationship("Device", back_populates="owner")


# =============================================================================
# Device
# =============================================================================

class Device(Base):
    __tablename__ = "devices"

    device_id = Column(String(30), primary_key=True)
    cpu_serial = Column(String(20), nullable=True)
    owner_user_id = Column(
        UUID(as_uuid=True), ForeignKey("users.user_id"), nullable=True,
    )
    factory_token_hash = Column(String(64), nullable=False)
    api_token = Column(String(255), nullable=True)
    token_expires_at = Column(DateTime(timezone=True), nullable=True)
    status = Column(
        String(20), nullable=False, server_default=text("'active'"),
    )
    plan_type = Column(
        String(20), nullable=False, server_default=text("'consumer'"),
    )
    notification_target = Column(String(500), nullable=True)
    detection_targets = Column(String(500), nullable=True)
    created_at = Column(
        DateTime(timezone=True), nullable=False,
        server_default=text("CURRENT_TIMESTAMP"),
    )
    last_seen = Column(DateTime(timezone=True), nullable=True)

    __table_args__ = (
        CheckConstraint(
            "status IN ('active', 'suspended')",
            name="devices_status_check",
        ),
        CheckConstraint(
            "plan_type IN ('consumer', 'ultimate')",
            name="devices_plan_type_check",
        ),
    )

    owner = relationship("User", back_populates="devices")
    events = relationship("DetectionEvent", back_populates="device")
    location_history = relationship("LocationHistory", back_populates="device")


# =============================================================================
# DetectionEvent (Phase 1.1: UUID v7 PK, payload_json, received_at)
# =============================================================================

class DetectionEvent(Base):
    """
    不変の事実テーブル。一度挿入されたら更新しない。
    event_id はデバイス側で生成した UUID v7（RFC 9562）。
    """
    __tablename__ = "detection_events"

    # --- GPS / Location fields (Phase 2 EDAS) ---
    latitude = Column(Numeric(10, 7), nullable=True)
    longitude = Column(Numeric(11, 7), nullable=True)
    altitude_m = Column(Numeric(7, 1), nullable=True)
    fix_method = Column(String(20), nullable=True)
    accuracy_m = Column(Numeric(8, 1), nullable=True)
    location_source = Column(String(20), nullable=True)
    time_source = Column(String(20), nullable=True)
    time_confidence = Column(String(10), nullable=True)

    # --- Phase 1.1: UUID v7 をデバイスが生成、PKとして受け取る ---
    event_id = Column(
        UUID(as_uuid=True), primary_key=True,
        comment="UUID v7 generated by edge device",
    )

    device_id = Column(
        String(30), ForeignKey("devices.device_id"), nullable=False,
    )
    event_type = Column(
        String(32), nullable=False, server_default=text("'detection'"),
        comment="detection / heartbeat / alert etc.",
    )
    occurred_at = Column(
        DateTime(timezone=True), nullable=False,
        server_default=text("CURRENT_TIMESTAMP"),
        comment="デバイス側の検知時刻",
    )
    received_at = Column(
        DateTime(timezone=True), nullable=False,
        server_default=text("CURRENT_TIMESTAMP"),
        comment="サーバ受信時刻",
    )

    # --- 構造化フィールド（ダッシュボード互換） ---
    detection_type = Column(String(20), nullable=True)
    confidence = Column(Numeric(5, 4), nullable=True)
    image_path = Column(String(500), nullable=True)
    image_url = Column(String(255), nullable=True)

    # --- IP / Geolocation ---
    ip_address = Column(String(45), nullable=True)
    ip_geolocation_region = Column(String(100), nullable=True)
    distance_from_registered_km = Column(Numeric(10, 3), nullable=True)
    location_mismatch = Column(
        Boolean, nullable=False, server_default=text("false"),
    )

    # --- Phase 1.1: 生ペイロード保存 ---
    payload_json = Column(
        JSONB, nullable=True,
        comment="デバイスから受信した生JSON（監査・デバッグ用）",
    )

    # --- Relationships ---
    device = relationship("Device", back_populates="events")
    delivery = relationship(
        "EventDelivery", back_populates="event", uselist=False,
    )


# =============================================================================
# EventDelivery (Phase 1.1: 可変の配送状態テーブル)
# =============================================================================

class EventDelivery(Base):
    """
    可変の配送状態テーブル。
    エッジ側のローカルDBにも同等のテーブルを持つ（将来）。
    サーバ側では受信確認の記録として使用。
    """
    __tablename__ = "event_delivery"

    event_id = Column(
        UUID(as_uuid=True),
        ForeignKey("detection_events.event_id"),
        primary_key=True,
    )
    state = Column(
        String(16), nullable=False, server_default=text("'received'"),
        comment="received / processing / completed / failed",
    )
    retry_count = Column(
        Integer, nullable=False, server_default=text("0"),
        comment="デバイスが報告したリトライ回数（X-Retry-Count）",
    )
    last_attempt_at = Column(
        DateTime(timezone=True), nullable=True,
        comment="デバイス側の最終送信試行時刻",
    )
    acked_at = Column(
        DateTime(timezone=True), nullable=True,
        comment="サーバが受理した時刻",
    )

    __table_args__ = (
        CheckConstraint(
            "state IN ('received', 'processing', 'completed', 'failed')",
            name="event_delivery_state_check",
        ),
    )

    event = relationship("DetectionEvent", back_populates="delivery")


# =============================================================================
# LocationHistory (変更なし)
# =============================================================================

class LocationHistory(Base):
    __tablename__ = "location_history"

    id = Column(Integer, primary_key=True, autoincrement=True)
    device_id = Column(
        String(30), ForeignKey("devices.device_id"), nullable=False,
    )
    lat = Column(Numeric(10, 8), nullable=False)
    lon = Column(Numeric(11, 8), nullable=False)
    accuracy = Column(Numeric(8, 2), nullable=True)
    registered_at = Column(
        DateTime(timezone=True), nullable=False,
        server_default=text("CURRENT_TIMESTAMP"),
    )
    registered_by = Column(
        UUID(as_uuid=True), ForeignKey("users.user_id"), nullable=False,
    )
    active_flag = Column(
        Boolean, nullable=False, server_default=text("true"),
    )
    ip_address = Column(INET, nullable=True)
    user_agent = Column(String(255), nullable=True)

    device = relationship("Device", back_populates="location_history")

class EventMedia(Base):
    __tablename__ = "event_media"

    media_id = Column(UUID(as_uuid=True), primary_key=True, server_default=text("gen_random_uuid()"))
    event_id = Column(UUID(as_uuid=True), ForeignKey("detection_events.event_id"), nullable=False, index=True)
    media_type = Column(String(16), nullable=False)
    upload_status = Column(String(16), nullable=False, server_default="completed")
    codec = Column(String(16))
    resolution = Column(String(16))
    duration_sec = Column(Numeric(5, 1))
    file_size_bytes = Column(Integer)
    sha256_hash = Column(String(64))
    storage_path = Column(String(500))
    uploaded_at = Column(DateTime(timezone=True))
    created_at = Column(DateTime(timezone=True), server_default=text("now()"))

    __table_args__ = (
        UniqueConstraint("event_id", "media_type", name="uq_event_media"),
        CheckConstraint("upload_status IN ('pending', 'uploading', 'completed', 'failed')", name="chk_upload_status"),
        CheckConstraint("media_type IN ('thumbnail', 'video')", name="chk_media_type"),
    )


# =============================================================================
# DeviceSubscriber (Phase 19)
# =============================================================================

class DeviceSubscriber(Base):
    __tablename__ = "device_subscribers"

    id = Column(Integer, primary_key=True, autoincrement=True)
    device_id = Column(
        String(30),
        ForeignKey("devices.device_id", ondelete="CASCADE"),
        nullable=False,
    )
    channel = Column(String(10), nullable=False)
    target = Column(String(255), nullable=False)
    label = Column(String(100), nullable=True)
    enabled = Column(Boolean, nullable=False, server_default=text("true"))
    created_at = Column(
        DateTime(timezone=True), nullable=False,
        server_default=text("CURRENT_TIMESTAMP"),
    )
    updated_at = Column(
        DateTime(timezone=True), nullable=False,
        server_default=text("CURRENT_TIMESTAMP"),
    )

    __table_args__ = (
        UniqueConstraint(
            "device_id", "channel", "target",
            name="uq_device_subscribers_device_channel_target",
        ),
        CheckConstraint(
            "channel IN ('line', 'email', 'phone')",
            name="device_subscribers_channel_check",
        ),
    )
